# If you want you can donate to any of the following links, or any non-profit association

Alzheimer's Association: # https://www.alz.org/
Prevent Child Abuse America: # https://preventchildabuse.org/
National Alliance to End Homelessness: # https://endhomelessness.org/

